### PR TITLE
[Do Not Merge] Upgraded substrate and added the IPT pallet

### PR DESCRIPTION
**Pull request by arrudagates**
This PR adds the IPT pallet and also upgrades the Substrate version to the tag: monthly-2021-09+1.

### CODE REVIEW

**Comment by SHA888** [comment]
@arrudagates This is mean all pallets would be imported directly form our library right?

**Comment by arrudagates** [comment]
Yes, is that the wrong approach?

**Comment by SHA888** [comment]
I don't think it's wrong. But as far as my understanding from W3F discussion, we created library to be able to be used by the community so we don't hard coded InvArch logic on the pallet library. But I think we need to check about it with @Invarchitect first to make it sure.

**Comment by arrudagates** [comment]
If that's the case we can hardcode InvArch logic in a separate branch of the pallet library

**Comment by SHA888** [comment]
@arrudagates yes that would be one option. The other option is create our logic in our InvArch-node. I don't know which one is better. What do you think?

**Comment by Invarchitect** [comment]
The InvArch Pallet Library is what is being provided to the community. 

We want it to be setup almost exactly as the ORML provided by Acala. ORML is an open runtime module library that has the templates/pallets that the Acala team uses, but also available for the community. It's not tied to their node.

Instead, I believe they manually input the pallets into their node, separately.

**Comment by Invarchitect** [comment]
You can view the InvArch Pallet Library entirely separate from our Node.

When it comes to our node, and implementing the pallets found in the InvArch Pallet Library, we would manually add them to our node.

**Comment by Invarchitect** [comment]
I assumed we would create our logic in the InvArch-node, but if this would be a problem, or of there is a better way, then let me know.

**Comment by SHA888** [comment]
> I assumed we would create our logic in the InvArch-node, but if this would be a problem, or if there is a better way, then let me know.

I don't think we would have any problem with it. I'm assuming any library/framework can be implemented to any specific chain/node. In broader sense, ike Substrate was pulled out from Polkadot and then can be implemented to build any parachain.

**Review by SHA888 — APPROVED** [review]
Looks good

**Comment by arrudagates** [comment]
This PR will be refactored, do not merge.

**Comment by SHA888** [comment]
@arrudagates Noted

**Pull request closed without merging**
